// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPe4E1dzP6GxYs9wwBdvNax7RE-dEpkWk',
    appId: '1:386021855612:web:9c1b79d7b9d85518e314f9',
    messagingSenderId: '386021855612',
    projectId: 'catchcheck-63803',
    authDomain: 'catchcheck-63803.firebaseapp.com',
    storageBucket: 'catchcheck-63803.firebasestorage.app',
    measurementId: 'G-3QZVV6JB6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNp7xx9LvuEfY1MvZNA2PQdm-FmEU8S4',
    appId: '1:386021855612:android:a23a774fa8b07cf5e314f9',
    messagingSenderId: '386021855612',
    projectId: 'catchcheck-63803',
    storageBucket: 'catchcheck-63803.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrCJu-kDt0dIvqIO9j5sXZ65rN6ru3uCA',
    appId: '1:386021855612:ios:d6f18cf8980b9be6e314f9',
    messagingSenderId: '386021855612',
    projectId: 'catchcheck-63803',
    storageBucket: 'catchcheck-63803.firebasestorage.app',
    iosBundleId: 'com.example.fishcast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrCJu-kDt0dIvqIO9j5sXZ65rN6ru3uCA',
    appId: '1:386021855612:ios:d6f18cf8980b9be6e314f9',
    messagingSenderId: '386021855612',
    projectId: 'catchcheck-63803',
    storageBucket: 'catchcheck-63803.firebasestorage.app',
    iosBundleId: 'com.example.fishcast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPe4E1dzP6GxYs9wwBdvNax7RE-dEpkWk',
    appId: '1:386021855612:web:01f8277ec1effbe2e314f9',
    messagingSenderId: '386021855612',
    projectId: 'catchcheck-63803',
    authDomain: 'catchcheck-63803.firebaseapp.com',
    storageBucket: 'catchcheck-63803.firebasestorage.app',
    measurementId: 'G-HG7MXQQGJD',
  );
}
